services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "9101:9101"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./crates/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./tmp/prometheus/data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./tmp/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus