{
 "title": "Rosetta-Status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Blockchain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blockchain Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blockchain_info", "legendFormat": "{{label_name}}" }
   ]
  },
  { "title": "Sync Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Block vs Target Block",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 5 },
   "targets": [
    { "expr": "sync_current_index", "legendFormat": "Current Block" },
    { "expr": "sync_target_index", "legendFormat": "Target Block" }
   ]
  },
  {
   "title": "Target Block Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_target_index", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Block Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_block_index", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Block Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_block_timestamp", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Blocks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "block_rate", "legendFormat": "Block Rate" }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "transaction_rate", "legendFormat": "Transaction Rate" }
   ]
  }
 ]
}